name: Update Book Covers
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Update README with book covers
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BOOKS"
          feed_list: "https://www.goodreads.com/review/list_rss/148846744?shelf=read"
          max_post_count: 5
          template: '<a href="$url"><img src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/$guid/l/$guid.jpg" width="80px" height="120px" alt="$title" title="$title"/></a>'
          commit_message: "📚 Updated book covers"
          committer_username: "books-bot"
          committer_email: "action@github.com"
