name: Update Book Covers
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Update README with book covers
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BOOKS"
          feed_list: "https://www.goodreads.com/review/list_rss/148846744?shelf=read"
          max_post_count: 5
          template: '<a href="$url" title="$title"><div style="display:inline-block; width:80px; height:120px; background:#f0f0f0; border:1px solid #ddd; margin:2px; text-align:center; font-size:10px; padding:5px; box-sizing:border-box; overflow:hidden;"><strong>$title</strong></div></a>'          commit_message: "📚 Updated book covers"
          committer_username: "books-bot"
          committer_email: "action@github.com"
