name: Update Goodreads Reading List
on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Update README with Goodreads books
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "GOODREADS"
          feed_list: "https://www.goodreads.com/review/list_rss/148846744?shelf=read"
          max_post_count: 5
          template: "- 📖 **[$title]($url)**"
          commit_message: "📚 Updated reading list from Goodreads"
          committer_username: "goodreads-bot"
          committer_email: "action@github.com"
